---
- name: Upgrade Portainer's Server
  hosts: {{ host }}
  become: true
  tasks:
    - name: Stop Portainer container
      docker_container:
        name: portainer
        state: stopped
      ignore_errors: true

    - name: Remove Portainer container
      docker_container:
        name: portainer
        state: absent
      ignore_errors: true

    - name: Pull Portainer image
      docker_image:
        name: portainer/portainer-ee:latest
        source: pull

    - name: Run Portainer container
      docker_container:
        name: portainer
        image: portainer/portainer-ee:latest
        state: started
        restart_policy: always
        ports:
          - "8000:8000"
          - "9443:9443"
        volumes:
          - "/var/run/docker.sock:/var/run/docker.sock"
          - "portainer_data:/data"

