---
- name: Execute Python script
  hosts: all
  gather_facts: true

  tasks: 

    - name: Set Environment Variable
      environment:
        BOT_CONF_FILE: "/home/giacomo/Projects/teleBot/conf.json"
      # Add your task here that requires the environment variable
      # For example, running a command that uses the environment variable
      shell: echo $BOT_CONF_FILE
      register: output

    - name: Display Output
      debug:
        var: output.stdout
        
    - name: Run the Python script
      command: python3 /home/giacomo/Projects/teleBot/pullReleases.py
      become: false
