---
- name: Restart a Systemd Service
  hosts: target_group
  become: true  # Per ottenere privilegi sudo
  tasks:
    - name: Restart the specified service
      ansible.builtin.service:
        name: "{{ service_name }}"
        state: restarted
