---
- name: Avvia backup Restic su tutti gli host
  hosts: all
  gather_facts: no
  strategy: free

  vars:
    script_path: "{{ script_path }}"  # Variabile passata da Semaphore

  tasks:
    - name: Avvia lo script di backup in background
      ansible.builtin.shell: "nohup {{ script_path }} > /tmp/backup.log 2>&1 &"
      become: yes
