---
- name: Esegui uno script Bash con output timestamped
  hosts: all
  gather_facts: no
  strategy: free

  vars:
    script_path: "{{ script_path }}"  # Percorso dello script da eseguire

  tasks:
    - name: Esegui lo script come root e mostra output con timestamp
      ansible.builtin.shell: |
        sudo bash -c 'while IFS= read -r line; do
          echo "$(date "+%Y-%m-%d %H:%M:%S") $line"
        done < <({{ script_path }})'
      args:
        executable: /bin/bash
