---
- name: Esegui script Bash con monitoraggio stato
  hosts: all
  gather_facts: no
  strategy: free

  vars:
    script_path: "{{ script_path }}"

  tasks:
    - name: Avvia script e monitora fino a completamento
      ansible.builtin.shell: sudo {{ script_path }}
      async: 7200     # massimo 2 ore
      poll: 10        # controlla ogni 10 secondi
