---
- name: Esegui script Python pullReleases.py
  hosts: all
  become_user: "{{ local_user }}"
  vars:
    script_path: ""  # Valore predefinito, sovrascrivibile

  tasks:
    - name: Esegui lo script Python
      ansible.builtin.command:
        cmd: python3 {{ src_script }}
      register: result

    - name: Mostra l'output dello script
      ansible.builtin.debug:
        var: result.stdout
