---
- name: Avvia backup Restic su tutti gli host
  hosts: all
  gather_facts: no
  strategy: free

  vars:
    script_path: "{{ script_path }}"  # Variabile passata da Semaphore
    log_file: /tmp/backup.log

  tasks:
    - name: Esegui lo script di backup con log in tempo reale
      ansible.builtin.shell: |
        sudo bash -c '{
          while IFS= read -r line; do
            timestamped_line="$(date "+%Y-%m-%d %H:%M:%S") $line"
            echo "$timestamped_line" | tee -a {{ log_file }}
          done < <({{ script_path }})
        }'
      become: yes
      args:
        executable: /bin/bash
