---
- name: Esegui script Python pullReleases.py
  hosts: all
  become: true
  vars:
    script_path: ""  # Valore predefinito, sovrascrivibile

  tasks:
    - name: Assicurati che Python sia installato
      ansible.builtin.apt:
        name: python3
        state: present
        update_cache: yes

    - name: Esegui lo script Python
      ansible.builtin.command:
        cmd: python3 {{ src_script }}
      register: result

    - name: Mostra l'output dello script
      ansible.builtin.debug:
        var: result.stdout
