---
- name: Execute 'whoami' command
  hosts: all
  become: true

  tasks:
    - name: Run 'whoami' command
      command: whoami
      register: whoami_output

    - name: Display 'whoami' output
      debug:
        var: whoami_output.stdout
