---
- name: Execute 'whoami' command
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: Run 'whoami' command
      command: whoami
      register: whoami_output

    - name: Display 'whoami' output
      debug:
        var: whoami_output.stdout

    - name: Determine if 'apt' command is available
      command: which apt
      register: apt_check
      ignore_errors: true

    - name: Display result
      debug:
        msg: "'apt' command is {{ 'available' if apt_check.rc == 0 else 'not available' }}"

    - name: Check if root privileged commands can be run
    raw: id  # You can replace "id" with any other command you want to check.
    register: command_output
    changed_when: false
    ignore_errors: true
    become: true
    become_method: sudo  # Change this to "su" if "sudo" is not available on your system.

  - name: Print the command output
    debug:
      var: command_output
