- name: Verifica e avvia il tunnel VS Code
  hosts: all
  become_user: "{{ username }}"
  tasks:
    - name: Controlla lo stato del tunnel
      command: code tunnel status
      register: tunnel_status_output

    - name: Analizza lo stato del tunnel
      set_fact:
        tunnel_status: "{{ tunnel_status_output.stdout | from_json }}"

    - name: Avvia il tunnel se è disconnesso
      command: code tunnel start
      when: tunnel_status.tunnel.tunnel == "Disconnected"

