---
- name: Update System
  hosts: all
  become: true
  become_user: root

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Pause for 30 seconds
      pause:
        seconds: 30

    - name: Upgrade system packages
      apt:
        upgrade: dist
        autoremove: yes
        autoclean: yes
        clean: yes
