---
- name: Update System
  hosts: all
  become: true

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Pause for 5 seconds
      pause:
        seconds: 5

    - name: Upgrade system packages
      apt:
        upgrade: dist
        autoremove: yes
        autoclean: yes
        clean: yes
